# The name of the workflow, this will be displayed in the Actions section
name: Build Django app

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Global environment variables
env:
  Django__KeyVaultName: 'kv-animaladoption-dev'
  Django__Debug: 'False'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The friendly name for the job
    name: Build the web app

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets the desired Python version to ensure compatibility
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # Create a virtual environment to install packages into
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      # Install the required packages for the app
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Authenticate using a Service Principal
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.DEV_RG_SP }}

      # Bundles the static assets into the directory specified by the STATIC_ROOT option
      - name: Collect static assets
        run: python manage.py collectstatic

      # Run the tests
      - name: Run tests
        run: python manage.py test

      # Upload everything that isn't inside the virtual environment folder as an artifact called
      # 'django-app'
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: django-app
          path: |
            .
            !venv/
